packages:
  - "apps/*"
  - "packages/*"
  - "services/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  bcrypt: true
  prisma: true

catalog:
  typescript: "^5.9.2"
  zod: "^4.1.5"
