import { API_PREFIX } from "../config/constants.ts";

export { API_PREFIX };

export const API_PATHS = {
  admin: `${API_PREFIX}/admin`,
  adminBooking: `${API_PREFIX}/admin/bookings/:id`,
  adminBookingAssign: `${API_PREFIX}/admin/bookings/:id/assign`,
  adminBookingStatus: `${API_PREFIX}/admin/bookings/:id/status`,
  adminBookings: `${API_PREFIX}/admin/bookings`,
  adminCleaner: `${API_PREFIX}/admin/cleaners/:id`,
  adminCleanerStatus: `${API_PREFIX}/admin/cleaners/:id/status`,
  adminCleaners: `${API_PREFIX}/admin/cleaners`,
  adminCustomer: `${API_PREFIX}/admin/customers/:id`,
  adminCustomerStatus: `${API_PREFIX}/admin/customers/:id/status`,
  adminCustomers: `${API_PREFIX}/admin/customers`,
  adminDashboard: `${API_PREFIX}/admin/dashboard`,
  adminMe: `${API_PREFIX}/admin/me`,
  adminNotificationRead: `${API_PREFIX}/admin/notifications/:id/read`,
  adminNotifications: `${API_PREFIX}/admin/notifications`,
  adminNotificationsReadAll: `${API_PREFIX}/admin/notifications/read-all`,
  adminNotificationStream: `${API_PREFIX}/admin/notifications/stream`,
  adminReview: `${API_PREFIX}/admin/reviews/:id`,
  adminReviewHide: `${API_PREFIX}/admin/reviews/:id/hide`,
  adminReviews: `${API_PREFIX}/admin/reviews`,
  adminService: `${API_PREFIX}/admin/services/:id`,
  adminServiceArchive: `${API_PREFIX}/admin/services/:id/archive`,
  adminServices: `${API_PREFIX}/admin/services`,
  adminSettings: `${API_PREFIX}/admin/settings`,
  api: "/api",
  authForgotPassword: `${API_PREFIX}/auth/forgot-password`,
  authLogin: `${API_PREFIX}/auth/login`,
  authLogout: `${API_PREFIX}/auth/logout`,
  authRegister: `${API_PREFIX}/auth/register`,
  authResendVerification: `${API_PREFIX}/auth/resend-verification`,
  authResetPassword: `${API_PREFIX}/auth/reset-password`,
  authSession: `${API_PREFIX}/auth/session`,
  authVerifyEmail: `${API_PREFIX}/auth/verify-email`,
  customerBooking: `${API_PREFIX}/customer/bookings/:id`,
  customerBookings: `${API_PREFIX}/customer/bookings`,
  customerQuotes: `${API_PREFIX}/customer/quotes`,
  customerService: `${API_PREFIX}/customer/services/:slug`,
  customerServices: `${API_PREFIX}/customer/services`,
  health: "/health",
  ready: "/ready",
  root: "/",
  v1: API_PREFIX,
} as const;

export type ApiPath = (typeof API_PATHS)[keyof typeof API_PATHS];
