export const CUSTOMER_MUTATION_RATE_LIMIT_MAX = 20;
export const CUSTOMER_MUTATION_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const CUSTOMER_BOOKING_NOTES_MAX_LENGTH = 1_000;
export const CUSTOMER_BOOKING_ADDRESS_MIN_LENGTH = 3;
export const CUSTOMER_BOOKING_ADDRESS_MAX_LENGTH = 200;
export const CUSTOMER_BOOKING_LEAD_MS = 24 * 60 * 60 * 1000;
