export const API_SERVICE_NAME = "neatly-api";
export const API_DEFAULT_PORT = 4000;
export const API_DEFAULT_HOST = "0.0.0.0";
export const API_SHUTDOWN_TIMEOUT_MS = 10_000;

export const API_ERROR_CODES = {
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_INPUT: "INVALID_INPUT",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const HTTP_STATUS = {
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  INTERNAL_SERVER_ERROR: 500,
  METHOD_NOT_ALLOWED: 405,
  NOT_FOUND: 404,
  OK: 200,
  SERVICE_UNAVAILABLE: 503,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
} as const;

export const API_HEALTH_STATUS = {
  OK: "ok",
} as const;

export const DATABASE_HEALTH_STATUS = {
  CONNECTED: "connected",
  DISCONNECTED: "disconnected",
} as const;
