export const API_SERVICE_NAME = "neatly-api";
export const API_DEFAULT_PORT = 4000;
export const API_DEFAULT_HOST = "0.0.0.0";
export const SMTP_DEFAULT_HOST = "smtp-relay.brevo.com";
export const SMTP_DEFAULT_PORT = 587;
export const SMTP_SECURE_PORT = 465;
export const API_SHUTDOWN_TIMEOUT_MS = 10_000;
export const API_VERSION = "v1";
export const API_PREFIX = `/api/${API_VERSION}`;
export const API_JSON_BODY_LIMIT_BYTES = 131_072;
export const MEDIA_UPLOAD_MAX_BYTES = 5 * 1024 * 1024;
export const MEDIA_ALLOWED_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
] as const;
export const SUPABASE_SERVICES_THUMB_BUCKET_DEFAULT = "Services_Thumb";
export const API_REQUEST_ID_HEADER = "x-request-id";
export const API_REQUEST_ID_MAX_LENGTH = 128;

export const PAGINATION_DEFAULT_PAGE = 1;
export const PAGINATION_DEFAULT_LIMIT = 20;
export const PAGINATION_MAX_LIMIT = 100;
export const SORT_DIRECTIONS = ["asc", "desc"] as const;
export const SEARCH_QUERY_MAX_LENGTH = 120;
export const VALIDATION_FAILED_MESSAGE = "Validation failed.";
export const ADMIN_MUTATION_RATE_LIMIT_MAX = 60;
export const ADMIN_MUTATION_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const PUBLIC_NEWSLETTER_RATE_LIMIT_MAX = 3;
export const PUBLIC_NEWSLETTER_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const ADMIN_SSE_RATE_LIMIT_MAX = 30;
export const ADMIN_SSE_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const ADMIN_SSE_HEARTBEAT_MS = 25_000;
export const ADMIN_TEXT_MAX_LENGTH = 200;
export const ADMIN_LONG_TEXT_MAX_LENGTH = 8_000;

export const API_ERROR_CODES = {
  CONFLICT: "CONFLICT",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  EMAIL_UNVERIFIED: "EMAIL_UNVERIFIED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_INPUT: "INVALID_INPUT",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const HTTP_STATUS = {
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  CREATED: 201,
  FORBIDDEN: 403,
  INTERNAL_SERVER_ERROR: 500,
  METHOD_NOT_ALLOWED: 405,
  NO_CONTENT: 204,
  NOT_FOUND: 404,
  OK: 200,
  SERVICE_UNAVAILABLE: 503,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
  UNPROCESSABLE_ENTITY: 422,
  UNSUPPORTED_MEDIA_TYPE: 415,
} as const;

export const API_HEALTH_STATUS = {
  OK: "ok",
} as const;

export const DATABASE_HEALTH_STATUS = {
  CONNECTED: "connected",
  DISCONNECTED: "disconnected",
} as const;
